# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_auto_20171016_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseGroupDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('IsDelete', models.BooleanField(default=False)),
                ('DeletedOn', models.DateTimeField(blank=True, null=True)),
                ('DeletedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ExpenseGroupDetails_DeletedBy', to='MainApp.SplitUser')),
                ('ExpenseGroupID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ExpenseGroupID', to='MainApp.ExpenseGroup')),
                ('UserID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserID', to='MainApp.SplitUser')),
            ],
        ),
    ]
