# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_expensegroupdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250)),
                ('Amount', models.DecimalField(decimal_places=10, max_digits=10)),
                ('Notes', models.CharField(max_length=500, null=True)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ExpenseType', models.CharField(choices=[('Internet', 'Internet'), ('Shopping', 'Shopping'), ('Rent', 'Rent'), ('Bills', 'Bills')], default='Shopping', max_length=50)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('IsDelete', models.BooleanField(default=False)),
                ('DeletedOn', models.DateTimeField(blank=True, null=True)),
                ('ModifiedOn', models.DateTimeField(blank=True, null=True)),
                ('CreatedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Expense_CreatedBy', to='MainApp.SplitUser')),
                ('DeletedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Expense_DeletedBy', to='MainApp.SplitUser')),
                ('ModifiedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Expense_ModifiedBy', to='MainApp.SplitUser')),
                ('PaidByUserID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Expense_PaidByUserID', to='MainApp.SplitUser')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShareAmount', models.DecimalField(decimal_places=10, max_digits=10)),
                ('IsDelete', models.BooleanField(default=False)),
                ('DeletedOn', models.DateTimeField(blank=True, null=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('CreatedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ExpenseDetails_CreatedBy', to='MainApp.SplitUser')),
                ('DeletedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ExpenseDetails_DeletedBy', to='MainApp.SplitUser')),
                ('ExpenseGroupDetailsID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ExpenseDetails_ExpenseGroupDetailsID', to='MainApp.ExpenseGroupDetails')),
                ('ExpenseID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ExpenseDetails_ExpenseID', to='MainApp.Expense')),
            ],
        ),
    ]
